In [1]:
import pandas as pd
import numpy as np
df =pd.read_csv(r'G:\Data_pyt\SMSSpamCollection',sep='\t',names=['label','sms_message'])



In [3]:
df.head()


label                                        sms_message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df['label']=df.label.map({'ham':0,'spam':1})
print(df.shape)
df.head()

(5572, 2)


label                                        sms_message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [7]:
## Implementing bag of words in scikit learn 
from sklearn.feature_extraction.text import CountVectorizer
count_vector=CountVectorizer()  ## instantiation
print(count_vector)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)


count_vector.fit(document)

freq_matrix=pd.df(count_vector.transform(documents).toarray(),columns=count_vector.get_features_names())

In [9]:
### now working on spam data
from sklearn.model_selection import train_test_split
make X_train as the sms msg col of df , and target array as label

In [10]:
X_train, X_test,y_train,y_test=train_test_split(df['sms_message'],df['label'],random_state=1)
print('No of rows in total set :{}'.format(df.shape[0]))
print('No of rows in trainingl set :{}'.format(X_train.shape[0]))
print('No of rows in total set :{}'.format(X_test.shape[0]))

No of rows in total set :5572
No of rows in trainingl set :4179
No of rows in total set :1393


In [11]:
X_train.shape


(4179,)

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector= CountVectorizer()
#fit training data and return matrix
training_data =count_vector.fit_transform(X_train)
##transform test data and return matrix
testing_data=count_vector.transform(X_test)
training_data

<4179x7456 sparse matrix of type '<class 'numpy.int64'>'
	with 55209 stored elements in Compressed Sparse Row format>

In [15]:
## some other approach of NV exist such as MultinomialNB and GaussianNB
from sklearn.naive_bayes import MultinomialNB
naive_bayes=MultinomialNB()
naive_bayes.fit(training_data,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [17]:
predictions =naive_bayes.predict(testing_data)
predictions

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [19]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
print('Accuracy score:',format(accuracy_score(y_test,predictions)))
print("precision score",format(precision_score(y_test,predictions)))
print("recall score:",format(recall_score(y_test,predictions)))
print("f1 score ",format(f1_score(y_test,predictions)))

Accuracy score: 0.9885139985642498
precision score 0.9720670391061452
recall score: 0.9405405405405406
f1 score  0.9560439560439562


##### PYTHON PIPLELINE

In [2]:
df.head()
df =pd.read_csv(r'G:\Data_pyt\SMSSpamCollection',sep='\t',names=['','sms_message'])

label                                        sms_message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(df['sms_message'],
                                               df['label'],
                                               random_state=1)

In [12]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
count_vector= CountVectorizer()
from sklearn.naive_bayes import MultinomialNB
naive_bayes=MultinomialNB()

In [13]:
pipe1=Pipeline([('countvec',CountVectorizer()),
    ('classifier',MultinomialNB())])
               

In [14]:
### Carefully observe fit 
#we dont pass y_test i fit()

In [15]:
pipe1.fit(X_train,y_train)  ##  pipleline object does all the transformations and estimation

Pipeline(memory=None,
         steps=[('countvec',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('classifier',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [16]:
pipe1.predict_proba(X_test)

array([[9.97122551e-01, 2.87744864e-03],
       [9.99981651e-01, 1.83488846e-05],
       [9.97926987e-01, 2.07301295e-03],
       ...,
       [9.99998910e-01, 1.09026171e-06],
       [1.86697467e-10, 1.00000000e+00],
       [9.99999996e-01, 3.98279868e-09]])

#### Save python objects to use 

In [17]:
from sklearn.externals import joblib ## used for saving models as a pickle file(a binary file)

C:\Users\aksha.LAPTOP-KKEAULMJ\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [18]:
joblib.dump(pipe1,'my_model_pipeline.pkl')

['my_model_pipeline.pkl']

#### Loading Models

In [1]:
import pandas as pd
from sklearn.externals import joblib

C:\Users\aksha.LAPTOP-KKEAULMJ\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [2]:
mymodel=open('my_model_pipeline.pkl','rb')
pipe=joblib.load(mymodel)

In [8]:
my_msg=['today is last day of ML .Now lllll  last week of ML ','Next week is AI ', 'we are learnign pickiling today ','need PRACTICE',
        ' the a is ok LAST messaged went ']
my_df=pd.DataFrame({'message':my_msg})
    

In [9]:
my_df

message
0  today is last day of ML .Now lllll  last week ...
1                                   Next week is AI 
2                   we are learnign pickiling today 
3                                      need PRACTICE
4                    the a is ok LAST messaged went

In [10]:
pipe.predict_proba(my_df['message'])

array([[9.96908360e-01, 3.09163953e-03],
       [8.82728970e-01, 1.17271030e-01],
       [9.86488304e-01, 1.35116963e-02],
       [9.69542237e-01, 3.04577628e-02],
       [9.99911378e-01, 8.86216337e-05]])

In [11]:
pipe.classes_

array(['ham', 'spam'], dtype='<U4')